### PR TITLE
NAT GW Multi-AZ feature

### PR DESCRIPTION
**Pull request by gcp87zoi**

### CODE REVIEW

**Comment by emnavarro02** [comment]
Hi, @gcp87zoi, could you please update the documentation and changelog?

**Comment by gcp87zoi** [comment]
Hey @emnavarro02, Changelog and documentation has been updated. Please review

**Comment by emnavarro02** [comment]
Thanks for fixing it. Changes look good to me 🚀

**Review by emnavarro02 — APPROVED** [review]
LGTM

**Pull request merged**
